namespace:
  key: :tenants
  namespaces:
    - key: :dchbx
      namespaces:
      - key: :applications
        namespaces:
        - key: :enroll
          namespaces:
          - key: :features
            namespaces:
            - key: :individual_market
              settings:
              - key: :state_name
                title: 'State Name'
                description: 'State Name'
                type: :string
                value: 'District of Columbia'
                default: 'District of Columbia'
              - key: :state_abbreviation
                title: 'State Abbreviation'
                description: 'State Abbreviation'
                type: :string
                value: 'DC'
                default: 'DC'
              - key: :hbx_abbreviation
                title: "Hbx Abbreviation"
                type: :string
                value: "DC Health Benefit Exchange"
                default: "DC Health Benefit Exchange"
              - key: :nationwide_markets
                title: 'Nationwide Markets'
                type: :boolean
                value: true
                default: false
              namespaces:
              - key: :verification_outstanding_window
                settings:
                - key: :days
                  default: '0'
              - key: :verification_due
                settings:
                - key: :days
                  default: '95'  
              - key: :open_enrollment
                settings:
                - key: :start_on
                  default: <%= Date.new(2018,11,1) %>
                - key: :end_on
                  default: <%= Date.new(2019,01,31) %>
              - key: :upcoming_open_enrollment
                settings:
                - key: :start_on
                  default: <%= Date.new(2019,11,1) %>
                - key: :end_on
                  default: <%= Date.new(2020,01,31) %>