key: :tenants
namespaces:
  - key: :dchbx
    namespaces:
    - key: :enroll
      namespaces:  
      - key: :site
        settings:
        - key: copyright_period_start
          type: :string
          default: "2013"
        - key: policies_url
          type: :string
          default: "https://dchealthlink.com/"         
        - key: faqs_url
          type: :string
          default: "https://www.dchealthlink.com/Frequently-Asked-Questions"   
        - key: help_url
          type: :string
          default: "https://www.dchealthlink.com/help"  
        - key: business_resource_center_url
          type: :string
          default: "https://dchealthlink.com/smallbusiness/"    
        - key: nondiscrimination_notice_url
          type: :string
          default: "https://www.dchealthlink.com/nondiscrimination"