# We will add the following back in later, but they cause
#   a completely outsized amount of cop failures for the number of files:
# - db/seedfiles
# - lib/tasks
AllCops:
  Exclude:
    - './project_gems/effective_datatables-2.6.14/effective_datatables-2.6.14.gemspec'
    - './node_modules/**/*'
    - './db/seedfiles/**/*'
    - './lib/tasks/**/*'
    - './components/benefit_markets/db/seedfiles/**/*'
    - './components/benefit_sponsors/db/seedfiles/**/*'
    - './components/old_sponsored_benefits/**/*'
    - './eyes/enroll.eye.rb'

Rails:
  Enabled: true

Rails/ActiveRecordAliases:
  Enabled: false

Rails/FindBy:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Re-enable once other problems are solved
Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Metrics/LineLength:
  Max: 200

Style/BracesAroundHashParameters:
  Enabled: false

# We will want to turn this back on or customize it more fully
Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

require:
  - ./cops/lint/empty_rescue_clause.rb

# Deprecated
# Style/TrailingBlankLines:
#   Enabled: false
# AllCops:
#   RunRailsCops: true
