assertion_consumer_service_url: "<%= ENV['ASSERTION_CONSUMER_SERVICE_URL'] %>" 
assertion_consumer_logout_service_url: "<%= ENV['ASSERTION_CONSUMER_SERVICE_LOGOUT_URL'] %>" 
issuer: "<%= ENV['SAML_ISSUER'] %>"
idp_entity_id: "<%= ENV['IDP_ENTITY_ID'] %>"
idp_sso_target_url: "<%= ENV['IDP_SSO_TARGET_URL'] %>"
idp_slo_target_url:  "<%= ENV['IDP_SLO_TARGET_URL'] %>"
idp_cert:  "<%= ENV['IDP_CERTIFICATE'] %>"
name_identifier_format: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
idp_cert_fingerprint:  "<%= ENV['IDP_CERT_FINGERPRINT'] %>"
idp_cert_fingerprint_algorithm: "http://www.w3.org/2000/09/xmldsig#sha1"
curam_landing_page_url: "<%= ENV['LANDING_PAGE_URL'] %>"
saml_logout_url: "<%= ENV['LOGOUT_URL'] %>" 
account_conflict_url: "<%= ENV['ACCOUNT_CONFLICT_URL'] %>"
account_recovery_url: "<%= ENV['ACCOUNT_RECOVERY_URL'] %>"
iam_login_url: "<%= ENV['LOGIN_URL'] %>"
curam_broker_dashboard: "<%= ENV['BROKER_DASHBOARD_URL'] %>"
kp_pay_now_url: "https://"
kp_pay_now_issuer: "enroll"
kp_pay_now_private_key_location: "/var/key.pem"
kp_pay_now_x509_cert_location: "/var/cert.crt"
kp_pay_now_audience: "https://"
kp_pay_now_relay_state: "https://"
