<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags 'not @wip' --tags 'not @individual_enabled' --tags 'not @general_agency_enabled' --tags 'not @quoting_enabled'"
%>
default: <%= std_opts %>
wip: --tags @wip:11 --wip
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
screenshots: <%= std_opts %> SCREENSHOTS=true
