default: --format pretty --fail-fast --order random --strict --tags 'not @wip and not @broken and not @flaky' -r features --profile semaphoreci
everything: --format pretty --strict -r features
semaphoreci: -q
