default: --format pretty --fail-fast --retry 1 --order random --strict --tags 'not @wip and not @broken' -r features --profile semaphoreci
everything: --format pretty --strict -r features
semaphoreci: -q
