---
registry:
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :broker_quoting_tool
    features:
      - key: :flexible_contribution_model_for_bqt
        item: :contribution_model
        is_enabled: true
        settings:
        - key: :initial_application_period
          item: <%= Date.new(2020,03,01)..Date.new(2020,12,31) %>
        - key: :enabled_for_renewal_applications
          item: false
        - key: :employer_contribution_percent_minimum
          item: 0
        - key: :employer_family_contribution_percent_minimum
          item: 0

  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :initial_application
    features:
      - key: :flexible_contribution_model_for_initials
        item: :contribution_model
        is_enabled: true
        settings:
        - key: :application_period
          item: <%= Date.new(2020,03,01)..Date.new(2020,12,31) %>
        - key: :employee_participation_ratio_minimum
          item: 0