---
registry:
  - namespace:
      - :create_qle
    features:
      - key: :sep_types
        item: Operations::QualifyingLifeEventKind::Persist.new
        is_enabled: true
        meta:
          label: Create Sep Types
          content_type: :legend
          default: :''
          description: 'Create Sep Types'
          is_required: true
          is_visible: true
        settings:
          - key: :label
            item: 'Create Sep Types'
          - key: :start_on
            item: <%= ENV['start_on'] %>
            meta:
              label: Start Date
              content_type: :date
              default: ''
              description: Enter Start Date
              is_required: true
              is_visible: true
          - key: :end_on
            item: <%= ENV['end_on'] %>
            meta:
              label: End Date
              content_type: :date
              default: ''
              description: Enter End Date
              is_required: false
              is_visible: true
          - key: :title
            item: <%= ENV['title'] %>
            meta:
              label: Title
              content_type: :text_field
              default: ''
              description: Enter Title
              is_required: true
              is_visible: true
          - key: :tool_tip
            item: <%= ENV['tool_tip'] %>
            meta:
              label: Tool Tip
              content_type: :text_field
              default: ''
              description: Enter Toot Tip
              is_required: false
              is_visible: true
          - key: :pre_event_sep_in_days
            item: <%= ENV['pre_event_sep_in_days'] %>
            meta:
              label: Pre Event SEP( In Days )
              content_type: :number
              default: ''
              description: Enter Sep Start(In Days)
              is_required: true
              is_visible: true
          - key: :post_event_sep_in_days
            item: <%= ENV['post_event_sep_in_days'] %>
            meta:
              label: Post Event SEP( In Days )
              content_type: :number
              default: ''
              description: Enter Sep End( In Days )
              is_required: true
              is_visible: true
          - key: :market_kind
            item: <%= ENV[':market_kind'] %>
            meta:
              label: Market
              content_type: :radio_select
              enum: [{individual: "Individual"}, {shop: "Shop"}, {fehb: "Congress"}]
              default: :individual
              description: Select Market Kind
              is_required: true
              is_visible: true
          - key: :is_self_attested
            item: <%= ENV['is_self_attested'] %>
            meta:
              label: Self Attestation
              content_type: :radio_select
              default: true
              enum: [ {'true': 'Self-Service' }, { 'false': 'Admin Only'} ]
              description: 'Select Self Attestation Type'
              is_required: true
              is_visible: true
          - key: :reason
            item: <%= ENV['reason'] %>
            meta:
              label: Reason
              content_type: :select
              enum: []
              default: ''
              description: Select Reason
              is_required: true
              is_visible: true
          - key: :other_reason
            item: <%= ENV['other_reason'] %>
            meta:
              label: Other Reason
              content_type: :text_field
              default: ''
              description: Enter Other Reason
              is_required: true
              is_visible: true
          - key: :effective_on_kinds
            item: <%= ENV['effective_on_kinds'] %>
            meta:
              label: Effective On
              enum: [{date_of_event: Date of Event}, {first_of_month: First of Month}, {first_of_this_month: First of This Month}, {first_of_next_month: First of Next Month}, {fixed_first_of_next_month: Fixed First of Next Month}, {exact_date: Exact Date}]
              content_type: :checkbox_select
              default: ''
              description: Select Coverage Effective Type
              is_required: false
              is_visible: true
          - key: :termination_on_kinds
            item: <%= ENV['termination_on_kinds'] %>
            meta:
              label: Termination On
              enum: [{end_of_event_month: Last Day of Event Month}, {date_before_event: Day before Event}, {end_of_last_month_of_reporting: Last Day of Month before Reporting}, {end_of_reporting_month: Last Day of Reporting Month}, {exact_date: Exact Date}]
              content_type: :checkbox_select
              default: ''
              description: Select Termination Effective Type
              is_required: false
              is_visible: true
          - key: :coverage_effective_on
            item: <%= ENV['coverage_effective_on'] %>
            meta:
              label: Eligibility Start Date
              content_type: :date
              default: ''
              description: Enter Eligibility Start Date
              is_required: false
              is_visible: true
          - key: :coverage_end_on
            item: <%= ENV['coverage_end_on'] %>
            meta:
              label: Eligibility End Date
              content_type: :date
              default: ''
              description: Enter Eligibility End Date
              is_required: false
              is_visible: true
          - key: :is_visible
            item: <%= ENV['is_visible'] %>
            meta:
              label: Visibility
              content_type: :radio_select
              default: true
              enum: [ {'true': 'Customer & Admin' }, { 'false': 'Admin Only'} ]
              description: 'Select Visibility'
              is_required: true
              is_visible: true
          - key: :date_options_available
            item: <%= ENV['date_options_available'] %>
            meta:
              label: Date Options Available
              content_type: :radio_select
              default: true
              enum: [ {'true': 'True' }, { 'false': 'False'} ]
              description: 'Select Date Options Availabilty'
              is_required: true
              is_visible: true
          - key: :event_kind_label
            item: <%= ENV['event_kind_label'] %>
            meta:
              label: Event Label
              content_type: :text_field
              default: ''
              description: Enter Event Label
              is_required: true
              is_visible: true
      - key: :expire_sep_type
        item: Operations::QualifyingLifeEventKind::Transform.new
        is_enabled: true
      - key: :sort_sep_type
        item: Operations::QualifyingLifeEventKind::Sort.new
        is_enabled: true
