---
registry:
  - namespace:
      - :create_qle
    features:
      - key: :sep_types
        item: Operations::QualifyingLifeEventKind::Persist.new
        is_enabled: true
        meta:
          label: Create Sep Types
          content_type: :legend
          default: :''
          description: 'Create Sep Types'
          is_required: true
          is_visible: true
        settings:
          - key: :label
            item: 'Create Sep Types'
          - key: :start_on
            item: <%= ENV['start_on'] %>
            meta:
              label: Start Date *
              content_type: :date
              default: ''
              description: ''
              is_required: true
              is_visible: true
          - key: :end_on
            item: <%= ENV['end_on'] %>
            meta:
              label: End Date
              content_type: :date
              default: ''
              description: ''
              is_required: false
              is_visible: true
          - key: :title
            item: <%= ENV['title'] %>
            meta:
              label: SEP Name *
              content_type: :text_field
              default: ''
              description: ''
              is_required: true
              is_visible: true
          - key: :tool_tip
            item: <%= ENV['tool_tip'] %>
            meta:
              label: SEP Name Tool Tip
              content_type: :text_field
              default: ''
              description: ''
              is_required: false
              is_visible: true
          - key: :pre_event_sep_in_days
            item: <%= ENV['pre_event_sep_in_days'] %>
            meta:
              label: Days Eligible Before Event Date *
              content_type: :number
              default: ''
              description: ''
              is_required: true
              is_visible: true
          - key: :post_event_sep_in_days
            item: <%= ENV['post_event_sep_in_days'] %>
            meta:
              label: Days Eligible After Event Date *
              content_type: :number
              default: ''
              description: ''
              is_required: true
              is_visible: true
          - key: :market_kind
            item: <%= ENV[':market_kind'] %>
            meta:
              label: Market *
              content_type: :radio_select
              enum: [{individual: "Individual"}, {shop: "SHOP"}, {fehb: "Congress"}]
              default: :individual
              description: ''
              is_required: true
              is_visible: true
          - key: :is_self_attested
            item: <%= ENV['is_self_attested'] %>
            meta:
              label: Self Attestation *
              content_type: :radio_select
              default: true
              enum: [ {'true': 'Self-Service' }, { 'false': 'Admin Only'} ]
              description: ''
              is_required: true
              is_visible: true
          - key: :reason
            item: <%= ENV['reason'] %>
            meta:
              label: EDI Reason Code *
              content_type: :text_field
              default: ''
              description: ''
              is_required: true
              is_visible: true
          - key: :effective_on_kinds
            item: <%= ENV['effective_on_kinds'] %>
            meta:
              label: Effective Date Rules *
              enum: [{date_of_event: Date of Event},
              {first_of_this_month: First of Event Month},
              {fixed_first_of_next_month: First of Month after Event},
              {first_of_next_month: Event First of Next Month},   # 15 month rule
              {first_of_month_plan_selection: First of the Month following Plan Selection},
              {first_of_month: 15th of Month Plan Shopping},
              {first_of_reporting_month: First of Reporting Month},
              {fixed_first_of_next_month_reporting: First of Month after Reporting},
              {exact_date: Exact Date}]
              content_type: :checkbox_select
              default: ''
              description: ''
              is_required: false
              is_visible: true
          - key: :termination_on_kinds
            item: <%= ENV['termination_on_kinds'] %>
            meta:
              label: Termination On
              enum: [{end_of_event_month: Last Day of Event Month}, {date_before_event: Day before Event}, {end_of_last_month_of_reporting: Last Day of Month before Reporting}, {end_of_reporting_month: Last Day of Reporting Month}, {exact_date: Exact Date}]
              content_type: :checkbox_select
              default: ''
              description: ''
              is_required: false
              is_visible: true
          - key: :coverage_start_on
            item: <%= ENV['coverage_start_on'] %>
            meta:
              label: Eligibility Start Date
              content_type: :date
              default: ''
              description: ''
              is_required: false
              is_visible: true
          - key: :coverage_end_on
            item: <%= ENV['coverage_end_on'] %>
            meta:
              label: Eligibility End Date
              content_type: :date
              default: ''
              description: ''
              is_required: false
              is_visible: true
          - key: :is_visible
            item: <%= ENV['is_visible'] %>
            meta:
              label: Visibility *
              content_type: :radio_select
              default: true
              enum: [ {'true': 'Customer & Admin' }, { 'false': 'Admin Only'} ]
              description: ''
              is_required: true
              is_visible: true
          - key: :date_options_available
            item: <%= ENV['date_options_available'] %>
            meta:
              label: Date Options Available *
              content_type: :radio_select
              default: false
              enum: [ {'true': 'True' }, { 'false': 'False'} ]
              description: ''
              is_required: true
              is_visible: true
          - key: :event_kind_label
            item: <%= ENV['event_kind_label'] %>
            meta:
              label: Event Date Label *
              content_type: :text_field
              default: ''
              description: ''
              is_required: true
              is_visible: true
          - key: :qle_event_date_kind
            item: <%= ENV['qle_event_date_kind'] %>
            meta:
              label: SEP Eligibility Kind *
              content_type: :radio_select
              enum: [ {qle_on: 'Event Date' }, { submitted_at: 'Reported Date'} ]
              default: :qle_on
              description: ''
              is_required: true
              is_visible: true
      - key: :expire_sep_type
        item: Operations::QualifyingLifeEventKind::Transform.new
        is_enabled: true
        meta:
          label: Expire Sep Type
          content_type: :legend
          default: :''
          description: 'Expire Sep Types'
          is_required: true
          is_visible: true
        settings:
          - key: :end_on
            item: <%= ENV['end_on'] %>
            meta:
              label: ''
              content_type: :date
              default: ''
              description: ''
              is_required: true
              is_visible: true
      - key: :sort_sep_type
        item: Operations::QualifyingLifeEventKind::Sort.new
        is_enabled: true
