---
registry:
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_application
    features:
      - key: :reinstate_timeframe
        item: :reinstate_timeframe
        is_enabled: true
        settings:
          - key: :timeframe_months
            item: 12
