name: other engines
on: push

env:
  RSPEC_SPLIT_CONFIGURATION_PATH: 'ci/rspec-split-config.json'
  TEST_BOOSTERS_RSPEC_TEST_FILE_PATTERN: '{spec,components/benefit_markets/spec,components/benefit_sponsors,components/notifier,components/sponsored_benefits,components/transport_gateway,components/transport_profiles}/**/*_spec.rb'

engine:
  name: engine
  runs-on: ubuntu-latest
  strategy:
    matrix:
      engine-name:
        [
          'benefit_markets',
          'notifier',
          'sponsored_benefits',
          'transport_gateway',
          'transport_profiles',
        ]
  steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
    - uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: '3.6'
    - name: Restore Project Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: v5-${{ matrix.engine-name }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          v5-${{ matrix.engine-name }}-
    - name: bundle install
      run: |
        gem update --system --quiet --silent
        bundle config path vendor/bundle
        bundle install
        echo switching to ${{ matrix.engine-name }}
        cd components/${{ matrix.engine-name }}
        bundle config path ../../vendor/bundle
        echo testing caching
        echo installing ${{ matrix.engine-name }} dependencies
        bundle install
    - name: Restore Node Modules
      id: npm-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
    - name: yarn install
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: |
        yarn install
    - name: run webpack
      run: |
        echo bundle config
        bundle config path vendor/bundle
        NODE_ENV=test RAILS_ENV=test ./bin/webpack
    - name: test engine
      run: |
        root=`pwd -P`
        echo $root/components/${{ matrix.engine-name }}
        cd $root/components/${{ matrix.engine-name }}
        bundle config path ../../vendor/bundle
        bundle exec rspec --fail-fast
