name: rubocop
on: push

jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Cache Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: v2-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
          restore-keys: |
            v2-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Run rubocop
        run: |
          git config diff.renameLimit 800
          git fetch --no-tags --depth=1 origin master
          bundle exec rubocop-git origin/master | grep "no offenses detected"
